version: "3.9"

services:

  django:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: otp_django
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    networks:
      - otp_network
    restart: always

networks:
  otp_network:
    driver: bridge