version: "3.9"

services:
  postgres:
    image: postgres
    container_name: otp_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: otp
    volumes:
      - /var/data/postgres:/var/lib/postgresql/data
    networks:
      - otp_network
    restart: always

  django:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: otp_django
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - otp_network
    restart: always

networks:
  otp_network:
    driver: bridge